### ISSUE TITLE
LuckPerms & LockLogin

### ISSUE THREAD

**Issue by thfree** [KarmaConfigs/page#14]
LuckPerms & LockLogin

Good afternoon, the "lp editor" command stops working with your plugin 

My server:
   - paper-1.16.5-437.jar
   - LockLogin-1.0.4.2.jar
   - ClearLag-3.2.0.jar
   - Dynmap-3.1-beta6-spigot.jar
   - KeepChunks-1.6.7.jar
   - LuckPerms-Bukkit-5.2.92.jar
   - WorldBorder-2.1.0.jar

**Comment by typecek123** [comment]
Hello, I have the same problem

**Comment by KarmaConfigs** [comment]
Try disabling AdvancedFiltering

```yaml
AdvancedFiltering: false
```

in config.yml

**Comment by thfree** [comment]
I'll try to check. It may be worthwhile to clarify the command output is cut in the terminal. Example: 
![изображение](https://user-images.githubusercontent.com/13134495/105875360-c2dcf000-600e-11eb-970e-cb8563154413.png)

In the normal state, the link appears here.

![изображение](https://user-images.githubusercontent.com/13134495/105875790-472f7300-600f-11eb-891f-4a82ed45f5ab.png)

**Comment by KarmaConfigs** [comment]
> I'll try to check. It may be worthwhile to clarify the command output is cut in the terminal. Example:
> ![изображение](https://user-images.githubusercontent.com/13134495/105875360-c2dcf000-600e-11eb-970e-cb8563154413.png)
> 
> In the normal state, the link appears here.
> 
> ![изображение](https://user-images.githubusercontent.com/13134495/105875790-472f7300-600f-11eb-891f-4a82ed45f5ab.png)

I just found why this is happening, the next update will fix it, meanwhile you can disable AdvancedFiltering

**Comment by KarmaConfigs** [comment]
Fixed:

https://www.spigotmc.org/resources/gsa-locklogin.75156/update?update=383869
