### ISSUE TITLE
Is it problem?

### ISSUE THREAD

**Issue by typecek123** [KarmaConfigs/page#15]
Hello, this happened, it is problem or is it okay?
https://paste.hostify.cz/?518eda93d511ea1c#HyGb2qtWz22io66oFbrxnkFhSP4WMSLj4NUyVxM5Qchb

**Comment by KarmaConfigs** [comment]
This happens when the LockLogin alerts system ( LLAS ) can't make a connection with the file that contains the latest alert message, it's nothing important and you can ignore it
