### ISSUE TITLE
Duplicate Request to login on first connect.

### ISSUE THREAD

**Issue by narcarsiss** [KarmaConfigs/page#17]
Spamming chat with repeated message /login capcha

Does this around 8 times, Pushing up the MOTD preventing players from seeing help options available to them.

Displays (2) times before MOTD
Displays (6) times After the MOTD

![image](https://user-images.githubusercontent.com/3479268/111425583-1af6bf80-873f-11eb-8210-7b1b94b8cdf0.png)

**Comment by KarmaConfigs** [comment]
Answered in https://github.com/KarmaConfigs/LockLogin/issues/3#event-4473439271
