### ISSUE TITLE
May not start

### ISSUE THREAD

**Issue by SnowSwordScholar** [KarmaConfigs/page#21]
插件非常好，但有一个问题，我用的BC，每次重启时会下载locklogin.injar（莫名其妙地），可当您的下载服务器出问题时，整个服务器就会出现没有登录插件保护的情况
The plug-in is very good, but there is a problem. The BC(waterfall latest) I use will download locklogin.injar every time when it restarts (inexplicably), when your download server has a problem, the entire server will appear without login plug-in protection.
I translate via google

**Comment by KarmaConfigs** [comment]
I've been working to fix these problems, LockLogin should now use also backup hosts, so if any of the hosts LockLogin uses fails, another one will be used
