### ISSUE TITLE
Unusual traffic on your ip

### ISSUE THREAD

**Issue by Manosag17** [KarmaConfigs/page#23]
The plugin blocked me for 30 mins, how can i delete the block from the files?

**Comment by KarmaConfigs** [comment]
> The plugin blocked me for 30 mins, how can i delete the block from the files?

Sorry for late reply, I recommend you asking for support in [our discord](https://discord.gg/jRFfsdxnJR) next time.

The only way to "un-block" your account when LockLogin does is by restarting the server
