### ISSUE TITLE
Flying and aliases

### ISSUE THREAD

**Issue by PLKaratusPL** [KarmaConfigs/page#3]
Hi!
I've got two things.
First of all, after logging in to the server my flying is turned off, I do not want it to be so, it is troublesome. Can you fix it somehow?

The second issue is the proposal. Can you add aliases to commands like: /login, /register etc.?
I mean shortcuts to these commands. Eg.
/login - /l
/register - /reg

Ps. Sorry for my English. This is not my native language.

**Comment by KarmaConfigs** [comment]
Done, sorry for the delay, the next update ( 2.1.7 ) will be published soon with the fixes for these bugs:

(Plugin already had [/login - /l | /register - /r] but weren't working on Spigot)
Fly was being disabled when logging-registering and verifying with 2fa

**Comment by KarmaConfigs** [comment]
https://www.spigotmc.org/resources/gsa-locklogin.75156/updates
