### ISSUE TITLE
I've made a french tradution

### ISSUE THREAD

**Issue by Nem-developing** [KarmaConfigs/page#5]
If you whant to put it on spigot for french people ^^

---> https://github.com/Nem-developing/fr-locklogin-traduction

Best regards !

**Comment by KarmaConfigs** [comment]
:0

Many thanks :D

What's your Spigot account name, so I can add you to "contributors"?

**Comment by Nem-developing** [comment]
--> https://www.spigotmc.org/members/nem05.753001/

Thanks you so much ^^.
