### ISSUE TITLE
Error while reading a plugin message from BungeeCord

### ISSUE THREAD

**Issue by Yakushe** [KarmaConfigs/page#9]
Auth server error message every second, when log-in or registering:
![image](https://user-images.githubusercontent.com/44678554/85224308-be01ef00-b3e2-11ea-9d5c-0ea186f5fb44.png)

BungeeCord error message when switching server:
![image](https://user-images.githubusercontent.com/44678554/85224379-7af44b80-b3e3-11ea-9ae9-239f61592391.png)

**Comment by KarmaConfigs** [comment]
What version of LockLogin are you using?

**Comment by KarmaConfigs** [comment]
I found the error, an update with the fix will be released soon

**Comment by Yakushe** [comment]
Aww, sorry for not full of information.
I,m using Minecraft version: 1.15.2
LockLogin version: 3.3.1(last)

**Comment by KarmaConfigs** [comment]
Fixed (2 days ago) and published (now), sorry for the delay :(

https://www.spigotmc.org/resources/gsa-locklogin.75156/

**Comment by Yakushe** [comment]
No problem, thank you much!
